Update documentation about "Branch naming"
PRO2022-Heig/heigvd-pro-01 pull request #15
Opened 2022-04-04 12:56 UTC by HugoMendes98

Please see the *TODOs* in the markdown to validate/invalidate them.

2022-04-05 13:18 UTC, noahboegli approved these changes

2022-04-05 15:33 UTC, noahboegli requested changes

2022-04-05 15:33 UTC, noahboegli commented on documentation/process/git.md
> +New branches should look like: `dev/<feeature>/<name>`.
fix typo

2022-04-05 22:13 UTC, dgheig commented
@HugoMendes98 Except for the typo "feeature", I don't have any opinion as long as there is an agreement among developers.
Please clarify the naming with @noahboegli and if needed ask another dev's opinion.

2022-04-06 14:50 UTC, HugoMendes98 commented on documentation/process/git.md
> +- When the feature is complete on each branch, all its content should be available on the latest branch  <!-- TODO: or with another name? -->
Ok, TODO removed

2022-04-06 14:51 UTC, dgheig approved these changes

2022-04-06 14:52 UTC, noahboegli approved these changes

2022-04-06 14:56 UTC, merged