Groups & Events, Entity ID filter, security rules changes
PRO2022-Heig/heigvd-pro-01 pull request #24
Opened 2022-05-25 21:14 UTC by noahboegli

A melting pot of stuff

- Groups & Events entities
- Global search filter by ID on all entities
- Change of security policies

@HugoMendes98  @fterrani  Please check the security policies changes and tell me if that works for you in terms of (un)authenticated routes

Code coverage remains 100% with this PR: 

```
Code Coverage Report:       
  2022-05-25 21:04:12       
                            
 Summary:                   
  Classes: 100.00% (22/22)  
  Methods: 100.00% (135/135)
  Lines:   100.00% (265/265)
```

2022-05-26 13:01 UTC, nigelmann requested changes

2022-05-26 13:01 UTC, nigelmann commented on app/backend/src/Entity/AppUser.php
> +#[ApiFilter(SearchFilter::class, properties: ["emailAddress", "firstName", "lastName"])]
We should add partial for search filters
see [documentation](https://api-platform.com/docs/core/filters/#search-filter)

2022-05-26 13:01 UTC, nigelmann commented on app/backend/src/Entity/GroupUserMembership.php
> +//    collectionOperations: [
Please remove commented things

2022-05-26 13:09 UTC, nigelmann approved these changes

2022-05-27 16:40 UTC, nigelmann approved these changes

2022-05-29 11:06 UTC, dgheig reviewed
Nothing that I am concerned for approval. I just checked that it is still working and good news: it is.

2022-05-29 11:06 UTC, dgheig approved these changes

2022-05-29 11:38 UTC, heigvdgachetje approved these changes

2022-05-29 12:28 UTC, Kitsunemma approved these changes

2022-05-29 16:32 UTC, merged